GET localhost:8080/getrooms
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzdWtydSBwb2xhdCIsImV4cCI6MTU2NzEwNDEwNSwiaWF0IjoxNTY3MDg2MTA1fQ.Bb7Ol7oQFiMPitpI46ksg9s3j9N4vUMRqlwc4NCKJAas-uUgSsQX7PlvY-Uvwt2o5Wna0NJjSRL4zdKRu2TlUQ
###
POST http://localhost:8080/authenticate
Content-Type: application/json

{"username":"testUser","password":"testPass"}
###
POST http://localhost:8080/register
Content-Type: application/json

{
  "username":"testUser",
  "password": "testPass"
}
###
POST http://localhost:8080/createroom
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzdWtydSBwb2xhdCIsImV4cCI6MTU2NzA1MTA4MywiaWF0IjoxNTY3MDMzMDgzfQ.rUf9wlLwQK7w3ueg2PMjZmb-AJ8DkTeClhRxod9BG76-f-aUacVoIKRnlOKchr_Iq1B-fd7D2dYTGAXpMnkYng

{"name": "00000","adress": "111111"}
###
GET http://localhost:8080/avaiblerooms/20190718/20190719
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzdWtydSBwb2xhdCIsImV4cCI6MTU2NzA1MTA4MywiaWF0IjoxNTY3MDMzMDgzfQ.rUf9wlLwQK7w3ueg2PMjZmb-AJ8DkTeClhRxod9BG76-f-aUacVoIKRnlOKchr_Iq1B-fd7D2dYTGAXpMnkYng

###

GET http://localhost:8080/reservations
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzdWtydSBwb2xhdCIsImV4cCI6MTU2NzEwNDEwNSwiaWF0IjoxNTY3MDg2MTA1fQ.Bb7Ol7oQFiMPitpI46ksg9s3j9N4vUMRqlwc4NCKJAas-uUgSsQX7PlvY-Uvwt2o5Wna0NJjSRL4zdKRu2TlUQ

###
POST http://localhost:8080/createreserve
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0VXNlciIsImV4cCI6MTU2NzE3NjQ0OSwiaWF0IjoxNTY3MTU4NDQ5fQ.CWXx1wGCKfkFh6tOZp6FuviQ0d6U66Jfo-uYNapSsizx7M7Wx0qMKmWoZTD-Nb8CQKyT-Eb46swKFp8fLY4QAw


{"roomid": 10,"createdby": "testUser", "fromdate": 20190917, "todate": 20190918, "title": "Interview with sukru polat"}

###
POST http://localhost:8080/cancelreserve
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0VXNlciIsImV4cCI6MTU2NzE3NjQ0OSwiaWF0IjoxNTY3MTU4NDQ5fQ.CWXx1wGCKfkFh6tOZp6FuviQ0d6U66Jfo-uYNapSsizx7M7Wx0qMKmWoZTD-Nb8CQKyT-Eb46swKFp8fLY4QAw


{
  "id": 22,
  "roomid": 10,
  "createdby": "sukru polat",
  "fromdate": 20190915,
  "todate": 20190916,
  "title": "Interview with sukru polat"
}

###